feat: add ServiceFilter query
cloudoperators/heureka pull request #130
Opened 2024-08-08 08:55 UTC by MR2011

2024-08-08 09:03 UTC, MR2011 commented on internal/app/user.go
> +func (h *HeurekaApp) ListUniqueUserID(filter *entity.UserFilter, options *entity.ListOptions) ([]string, error) {
Maybe use plural? ListUniqueUserIDs

2024-08-08 09:06 UTC, MR2011 reviewed
@drochow please also review. I added a comment, but overall it looks good to me

2024-08-09 05:55 UTC, drochow requested changes
Good Job, 

The code looks clean and neat BUT: 

I think we are missing on all SQL queries a Grouping. 

Why should we call "ListServiceNames" and get multiple times the same service name returned? Then I could call the normal List function. 

After thinking about it and seeing the Implementation. I also think from the "Frontend" perspective it might makes even sense to not have a dedicated endpoint for that but rather a ListOption to only return unique results by e.g. ServiceName. Like a grouping parameter.  I'd still separate the logic then in the Backend as done here but on the API I really doubt an additional endpoint does make sense.

@MR2011 
WDYT?

2024-08-09 05:55 UTC, drochow commented on internal/app/service_test.go
> +		It("it return the results", func() {
I think the correct results in this case would imply that we have only unique names? 

I would recommend adding this to the test.

2024-08-09 05:55 UTC, drochow commented on internal/app/support_group_test.go
> +			heureka = app.NewHeurekaApp(db)
Same here i think we should add a uniqueness check

2024-08-09 05:55 UTC, drochow commented on internal/app/user_test.go
> +var _ = Describe("When listing User", Label("app", "ListUserNames"), func() {
When listing names of Users

2024-08-09 05:55 UTC, drochow commented on internal/app/user_test.go
> +			heureka = app.NewHeurekaApp(db)
Again uniqueness check?!

2024-08-09 05:55 UTC, drochow commented on internal/app/user_test.go
> +			heureka = app.NewHeurekaApp(db)
Add unique check?

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/service.go
> +	baseQuery := `
Are we sure this contains only unique service names? Isnt the GroupBy missing?

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/service_test.go
> +					By("returning the correct number of results", func() {
Thats again not expecting unique names here?

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/service_test.go
> +						By("returning the correct number of results", func() {
When getting service names and filtering for. service name I'm expecting 1 result. Why so complicated?

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/support_group.go
> +    SELECT SG.supportgroup_name FROM SupportGroup SG
This will return multiple times the same support group name no? 

I think we are missing a group by?

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/support_group_test.go
> +					By("returning the correct number of results", func() {
taking uniqueness not into account

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/support_group_test.go
> +					By("returning the correct names", func() {
uniqueness

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/support_group_test.go
> +						By("returning the correct number of results", func() {
should be always one when filtering for the name

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/support_group_test.go
> +			Context("and using a SupportGroupNames filter", func() {
not desciptive enought

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/user.go
> +    SELECT U.user_name FROM User U
Missing group by ?

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/user_test.go
> +				It("can fetch the items correctly", func() {
doesnt take into account uniqueness

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/user_test.go
> +						By("returning the correct number of results", func() {
should be always 1

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/user_test.go
> +						By("returning the correct names", func() {
should be compared with names given in filter

2024-08-09 05:55 UTC, drochow commented on internal/database/mariadb/user_test.go
> +					It("and using another filter", func() {
take into account uniqueness in results

2024-08-09 05:55 UTC, drochow commented on internal/e2e/service_filter_query_test.go
> +			It("returns correct serviceNames", func() {
Uniqueness

2024-08-09 05:55 UTC, drochow commented on internal/e2e/service_filter_query_test.go
> +				for _, name := range respData.ServiceFilterValues.ServiceName.Values {
uniquness

2024-08-09 05:55 UTC, drochow commented on internal/e2e/service_filter_query_test.go
> +				existingSupportGroupNames := lo.Map(seedCollection.SupportGroupRows, func(s mariadb.SupportGroupRow, index int) string {
uniqueness

2024-08-09 05:55 UTC, drochow commented on internal/e2e/service_filter_query_test.go
> +			It("returns correct userNames", func() {
uniqueness

2024-08-09 08:32 UTC, drochow commented
After discussing with @MR2011  I've got it. 

Lets keep it like it is for the Frontend devs 👍

2024-08-09 08:32 UTC, drochow submitted a review, later dismissed

2024-08-12 11:45 UTC, merged