feat(services): add aggregations
cloudoperators/heureka pull request #268
Opened 2024-09-27 14:09 UTC by MR2011

## Description
This PR adds the following two aggregations for services:
- Count of ComponentInstances
- Count of IssueMatches

## What type of PR is this? (check all applicable)

- [ x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Closes #249 

## Added tests?

- [ x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Tests:
- E2E testing metadata (aggregation)
- App testing ListServices with aggregation
- DB testing individual aggregation functions

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🤝 Documentation pages updated
- [x ] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

## Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes

2024-10-01 10:25 UTC, drochow commented on internal/database/mariadb/service.go
> +func (s *SqlDatabase) GetServicesWithComponentInstanceCount(filter *entity.ServiceFilter) ([]entity.ServiceWithAggregations, error) {
Actually, I like having specialized queries for that.

I think we should go 1 step further and do leave away the genralization for "serviceWithAggregation" that we've build previously. 

As this example shows aggregations can easily get wrong when you add additional aggregations and even making combinations of certain aggregated values impossible. 
As such we might should  consider each aggregation separate of each other?

2024-10-02 14:28 UTC, drochow requested changes

2024-10-02 14:28 UTC, drochow commented on internal/app/service/service_handler.go
> +	}
Do we really want to check that? 

When a certain service has a 0 count. Is it then still be listed with count = 0 ?

2024-10-02 14:28 UTC, drochow commented on internal/app/service/service_handler_test.go
>  	})
If we want to enforce the above with checking that the two counts where giving back results for the same set of services we should also add a test for that

2024-10-02 14:28 UTC, drochow commented on internal/database/mariadb/service_test.go
> +	})
Don't we need a test then here that is checking that for 0 counts the service is still listed? 

So I'm expecting 10 services even though they might not all have a count > 0.

2024-10-08 06:15 UTC, drochow requested changes
I still think we might can create 2 services (without anything) and we would expect them to come back no?

2024-10-08 06:18 UTC, drochow commented
@MR2011  Am I missing something? I think its just about calling: 

```golang
seeder.SeedServices(10)
```

in a test and check then if also the 0 count services are returned (if no filter is applied)

2024-10-08 08:01 UTC, MR2011 commented
> @MR2011 Am I missing something? I think its just about calling:
> 
> ```go
> seeder.SeedServices(10)
> ```
> 
> in a test and check then if also the 0 count services are returned (if no filter is applied)
That's tested here
https://github.com/cloudoperators/heureka/blob/963961c5fefa7a3825a4802b56f43af62c09bf59/internal/database/mariadb/service_test.go#L440-L465

2024-10-08 09:16 UTC, merged